# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude :     ['README.md']
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Conversion
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: "" # does not include hostname
baseurl :  /RadiantCollege

# Outputting
permalink:     date
#permalink:    /blog/:year/:title.html
paginate:      10
paginate_path: /page:num
timezone:      Asia/Calcutta

# Markdown Processors
kramdown:
input:          GFM
auto_ids:       true
footnote_nr:    1
entity_output:  as_char
toc_levels:     1..6
smart_quotes:   lsquo,rsquo,ldquo,rdquo
enable_coderay: false

# custom site settings
url:                       https://radiantcollege.github.io
title:                     "Welcome to Radiant College Dergaon website!"
description:               "A junior college in science, commerce and arts, providing quality education and inclusive development of the students."
google-site-verification:  ppp
collections:
docs:
output:                    true
#avatar:                    "/images/avatar-icon.jpg"


# --- Footer options --- #
#
# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
   name: Radiant College
   email: "principal@radiantcollege.com"
   domain: http://www.radiantcollege.com
   facebook: radiantcollegedergaon  # eg. daattali
   github: radiantcollege     # eg. daattali
   twitter: radiantcollege   # eg. daattali

# Select which links to show in the footer
footer-links-active:
   rss: false
   facebook: true
   email: true
   twitter: true
   github: true
   linkedin: false
   stackoverflow: false

url-pretty: "radiantcollege.com"

# Plugins
whitelist: []
gems: [jekyll-less, jekyll-paginate, jekyll-feed, jekyll-mentions, jekyll-sitemap]

defaults:
-
    scope:
      path: "" # an empty string here means all files in the project
      type: posts # previously `post` in Jekyll 2.2. #other values pages, collections and drafts
    values:
      layout: default
      comments: true
-
    scope:
      path: ""
    values:
      layout: default
      show-avatar: true
